### ISSUE TITLE
Local Dev Environment

### ISSUE THREAD

**Issue by tedmarov** [tiki/l0-storage#21]
# # Task List

- [ ] Need to get the worker function running in a container with CloudFlare's wrangler CLI. 
- [ ] Dockerfile under worker/upload needs to be finished so that NodeJS app can run in a container.
- [ ] Container for MinIO needs to be finished so that we can use it instead of production storage (Currently uses the S3-compatible Wasabi SaaS).
- [ ] Couple of code and settings changes to point the services to the proper local endpoints.
